<?php
/**
 * Webino (http://webino.sk/)
 *
 * @link        https://github.com/webino/WebinoDebug/ for the canonical source repository
 * @copyright   Copyright (c) 2014-2015 Webino, s. r. o. (http://webino.sk/)
 * @license     BSD-3-Clause
 */

namespace WebinoDebug\Options;

/**
 * Generated by PHPUnit_SkeletonGenerator
 */
class DebuggerOptionsTest extends \PHPUnit_Framework_TestCase
{
    public function testAssertDefaultOptions()
    {
        $options = new DebuggerOptions;

        $this->assertTrue($options->isEnabled());
        $this->assertNull($options->getMode());
        $this->assertFalse($options->hasBar());
        $this->assertTrue($options->isStrict());
        $this->assertSame(realpath('data/log'), $options->getLog());
        $this->assertSame('', $options->getEmail());
        $this->assertSame(10, $options->getMaxDepth());
        $this->assertSame(300, $options->getMaxLen());
    }

    public function testSettersAndGetters()
    {
        $cfg = [
            'enabled'     => false,
            'mode'        => true,
            'bar'         => true,
            'strict'      => false,
            'log'         => 'data',
            'email'       => 'test@example.com',
            'maxDepth'    => 5,
            'maxLen'      => 170,
        ];

        $options = new DebuggerOptions($cfg);

        $this->assertFalse($options->isEnabled());
        $this->assertTrue($options->getMode());
        $this->assertTrue($options->hasBar());
        $this->assertFalse($options->isStrict());
        $this->assertSame(realpath($cfg['log']), $options->getLog());
        $this->assertSame($cfg['email'], $options->getEmail());
        $this->assertSame($cfg['maxDepth'], $options->getMaxDepth());
        $this->assertSame($cfg['maxLen'], $options->getMaxLen());
    }
}
