<?php
/**
 * Webino (http://webino.sk/)
 *
 * @link        https://github.com/webino/WebinoDebug/ for the canonical source repository
 * @copyright   Copyright (c) 2014 Webino, s. r. o. (http://webino.sk/)
 * @license     BSD-3-Clause
 */

namespace WebinoDebug\Factory;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-10-18 at 01:05:38.
 */
class ModuleOptionsFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ModuleOptionsFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ModuleOptionsFactory;
    }

    /**
     * @covers WebinoDebug\Factory\ModuleOptionsFactory::createService
     */
    public function testCreateService()
    {
        $config   = ['webino_debug' => []];
        $services = $this->getMock('Zend\ServiceManager\ServiceManager');

        $services->expects($this->once())
            ->method('get')
            ->with('Config')
            ->will($this->returnValue($config));

        $options = $this->object->createService($services);
        $this->assertInstanceOf('WebinoDebug\Options\ModuleOptions', $options);
    }
}
