<?php
/**
 * Webino (http://webino.sk/)
 *
 * @link        https://github.com/webino/WebinoDebug/ for the canonical source repository
 * @copyright   Copyright (c) 2014-2015 Webino, s. r. o. (http://webino.sk/)
 * @license     BSD-3-Clause
 */

namespace WebinoDebug\Factory;

use WebinoDebug\Options\ModuleOptions;
use Zend\ServiceManager\ServiceManager;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-10-18 at 01:05:38.
 */
class ModuleOptionsFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers WebinoDebug\Factory\ModuleOptionsFactory::createService
     */
    public function testCreateService()
    {
        $config = ['webino_debug' => []];
        $services = $this->getMock(ServiceManager::class);

        $services->expects($this->once())
            ->method('get')
            ->with('Config')
            ->will($this->returnValue($config));

        $factory = new ModuleOptionsFactory;
        /** @var ServiceManager $services */
        $options = $factory->createService($services);
        $this->assertInstanceOf(ModuleOptions::class, $options);
    }
}
