<?php
/**
 * Webino (http://webino.sk/)
 *
 * @link        https://github.com/webino/WebinoDebug/ for the canonical source repository
 * @copyright   Copyright (c) 2014 Webino, s. r. o. (http://webino.sk/)
 * @license     BSD-3-Clause
 */

namespace WebinoDebug\Tracy\Workaround;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-10-18 at 01:08:11.
 */
class DisabledBarTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DisabledBar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DisabledBar;
    }

    /**
     * @covers WebinoDebug\Tracy\Workaround\DisabledBar::addPanel
     */
    public function testAddPanel()
    {
        $this->object->addPanel();
    }

    /**
     * @covers WebinoDebug\Tracy\Workaround\DisabledBar::getPanel
     */
    public function testGetPanel()
    {
        $this->object->getPanel();
    }

    /**
     * @covers WebinoDebug\Tracy\Workaround\DisabledBar::render
     */
    public function testRender()
    {
        $this->object->render();
    }
}
